# Generated by Django 3.1 on 2021-07-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
