# Generated by Django 3.1 on 2021-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0002_auto_20210714_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='time',
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('Найти работника', 'Найти работника'), ('Найти работу', 'Найти работу')], default='Активна', max_length=30, verbose_name='Статус'),
        ),
    ]
