# Generated by Django 3.1 on 2021-07-22 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dir', '0003_auto_20210716_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='dir.review')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dir.resume')),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
