# Generated by Django 3.1 on 2021-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0005_auto_20210722_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
