# Generated by Django 3.1 on 2021-07-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0006_auto_20210726_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default=1, upload_to='products', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
